### ISSUE TITLE
Problem with self.ws.recv()

### ISSUE THREAD

**Issue by remy-lavabre** [Frankkkkk/python-daikin-altherma#11]
Good morning,
When using a Raspberry Pi, it very regularly happens that result = json.loads(self.ws.recv()) in def _requestValue(self, item: str, output_path: str, payload=None): "blocks" execution.

Everything is blocked and only a "CTRL C" allows you to get out!
From the tests carried out, it is ws.recv () which is causing the problem.

Sometimes everything works, sometimes it blocks for an indefinite time without giving any error !

Maybe it's a timeout that's causing the problem?
Is there a solution to fix this??
THANKS

**Comment by Frankkkkk** [comment]
Should be fixed in 0.3.3. Thanks
