### ISSUE TITLE
Problem with .schedule_list_heating() function

### ISSUE THREAD

**Issue by remy-lavabre** [Frankkkkk/python-daikin-altherma#6]
Line 245:  out_schedules.append(self._unmarshall_schedule(schedule))
Line 308:  ctemp = float(ctemp)/10
Line 344:  print(pac_daikin.schedule_list_heating())

The return : 

/m2m:rsp/pc/m2m:cin/con
RES: >>> {'m2m:rsp': {'rsc': 2000, 'rqi': '68ce2', 'to': 'python-daikin-altherma', 'fr': '/[0]/MNAE/1/Schedule/List/Heating/la', 'pc': {'m2m:cin': {'rn': '00000008', 'ri': '003f_00000008', 'pi': '003f', 'ty': 4, 'ct': '20231013T145336Z', 'lt': '20231013T145336Z', 'st': 8, 'con': '{"data":["$NULL|0|0700,200;0900,180;1700,200;2300,180;,;,;0700,200;0900,180;1700,200;2300,180;,;,;0700,200;0900,180;1700,200;2300,180;,;,;0700,200;0900,180;1700,200;2300,180;,;,;0700,200;0900,180;1700,200;2300,180;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,","$NULL|0|0700,200;0900,180;1200,200;1400,180;1700,200;2300,180;0700,200;0900,180;1200,200;1400,180;1700,200;2300,180;0700,200;0900,180;1200,200;1400,180;1700,200;2300,180;0700,200;0900,180;1200,200;1400,180;1700,200;2300,180;0700,200;0900,180;1200,200;1400,180;1700,200;2300,180;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,","$NULL|0|0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,;0800,200;2300,180;,;,;,;,","LAVABRE|1|0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;,;,;0330,200;1800,180;,;,;0000,180;0000,180","$NULL|1|0010,120;0000,180;0000,180;0000,180;0000,180;0000,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,","$NULL|1|,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,;,"]}'}}}}
/home/remy/Téléchargements/python-daikin-altherma-0.2.0/daikin_altherma/__init__.py:55: DeprecationWarning: The dpath.util package is being deprecated. All util functions have been moved to dpath package top level.
  return dpath.util.get(result, output_path)
Traceback (most recent call last):
  File "/home/remy/Téléchargements/python-daikin-altherma-0.2.0/daikin_altherma/__init__.py", line 344, in <module>
    print(pac_daikin.schedule_list_heating())
  File "/home/remy/Téléchargements/python-daikin-altherma-0.2.0/daikin_altherma/__init__.py", line 245, in schedule_list_heating
    out_schedules.append(self._unmarshall_schedule(schedule))
  File "/home/remy/Téléchargements/python-daikin-altherma-0.2.0/daikin_altherma/__init__.py", line 308, in _unmarshall_schedule
    ctemp = float(ctemp)/10
ValueError: could not convert string to float: ''

**Comment by Frankkkkk** [comment]
Hi Remy,
The fix is on the MR #5 . I'll release a new version asap.
Cheers

**Comment by Frankkkkk** [comment]
v0.3.0 is out :-)
