### ISSUE TITLE
To add.. .Holiday mode

### ISSUE THREAD

**Issue by remy-lavabre** [Frankkkkk/python-daikin-altherma#9]
@property
    def holiday_state(self) -> bool:
        """ Returns if holiday state active or not """
        return self._requestValueHP("1/Holiday/HolidayState

def set_holiday (self, holiday_active: bool):
        """ Whether to turn the holiday mode on(True) or off(False).
        You can confirm that it works by calling self.holiday_state
        """
        mode_dict = {
            True: 1,
            False: 0,
        }

        payload = {
            'con': mode_dict[holiday_active],
            'cnf': 'text/plain:0',
        }

        self._requestValueHP("1/Holiday/HolidayState", "/", payload)

**Comment by Frankkkkk** [comment]
Thanks !
